name: Daily Account Insights Collection

on:
  schedule:
    # 毎日 09:00 JST (UTC 00:00)
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      target_date:
        description: '対象日付 (YYYY-MM-DD, 空の場合は今日)'
        required: false
        type: string
      target_accounts:
        description: '対象アカウント (カンマ区切り, 空の場合は全アカウント)'
        required: false
        type: string
      force_update:
        description: '既存データの強制上書き'
        required: false
        type: boolean
        default: false

jobs:
  collect-account-insights:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r backend/requirements.txt
        
    - name: Validate environment
      run: |
        cd backend
        python -c "
        import os
        required_vars = ['DATABASE_URL']
        missing = [var for var in required_vars if not os.getenv(var)]
        if missing:
            print(f'Missing required environment variables: {missing}')
            exit(1)
        print('Environment validation passed')
        "
        
    - name: Run account insights collection
      run: |
        cd backend
        python scripts/github_actions/account_insights_collector.py \
          --target-date "${{ github.event.inputs.target_date }}" \
          --target-accounts "${{ github.event.inputs.target_accounts }}" \
          --force-update ${{ github.event.inputs.force_update }} \
          --notify-slack \
          --log-level INFO
          
    - name: Upload execution logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: account-insights-logs-${{ github.run_id }}
        path: backend/logs/github_actions/
        retention-days: 30
        
    - name: Notify on failure
      if: failure()
      run: |
        cd backend
        python scripts/github_actions/shared/notification_service.py \
          --type failure \
          --workflow "daily-account-insights" \
          --run-id "${{ github.run_id }}" \
          --message "Account insights collection failed"