name: Manual Instagram Data Collection

on:
  workflow_dispatch:
    inputs:
      target_date:
        description: 'Target date for data collection (YYYY-MM-DD)'
        required: true
        type: string
      account_filter:
        description: 'Account username to collect (leave empty for all accounts)'
        required: false
        type: string
      dry_run:
        description: 'Dry run mode (test without saving to database)'
        required: false
        type: boolean
        default: false

jobs:
  collect-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt
        
    - name: Validate target date
      run: |
        if ! date -d "${{ github.event.inputs.target_date }}" >/dev/null 2>&1; then
          echo "Invalid date format: ${{ github.event.inputs.target_date }}"
          exit 1
        fi
        
    - name: Run manual data collection
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        INSTAGRAM_ACCESS_TOKENS: ${{ secrets.INSTAGRAM_ACCESS_TOKENS }}
        FACEBOOK_APP_ID: ${{ secrets.FACEBOOK_APP_ID }}
        FACEBOOK_APP_SECRET: ${{ secrets.FACEBOOK_APP_SECRET }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
        TARGET_DATE: ${{ github.event.inputs.target_date }}
        ACCOUNT_FILTER: ${{ github.event.inputs.account_filter }}
        DRY_RUN: ${{ github.event.inputs.dry_run }}
      run: |
        cd backend
        python scripts/collect_daily_data.py
        
    - name: Notify completion
      if: always()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        text: |
          📊 Manual Instagram data collection completed
          Target Date: ${{ github.event.inputs.target_date }}
          Account Filter: ${{ github.event.inputs.account_filter || 'All accounts' }}
          Dry Run: ${{ github.event.inputs.dry_run }}
          Status: ${{ job.status }}